ARG PROJECT_ID
ARG FOLDER
ARG BASE_REPO_NAME

FROM us-east4-docker.pkg.dev/${PROJECT_ID}/${FOLDER}/${BASE_REPO_NAME}:mssql-1.0

LABEL maintainer="Suren Meesala <smeesala@digitalriver.com>"

ADD ./src/main/scripts/* ./
ADD ./src/main/python/* ./
ADD ./src/test/python/* ./
ADD ./*.conf ./
ADD ./src/main/resources/*.properties /resources/
RUN dos2unix *.sh
RUN chmod +x *.sh
